# Generated by Django 5.2.3 on 2025-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20),
        ),
    ]
